# Site settings
title: Clinical Advisory Solutions
email: deborah.roy@clinicaladvisorysolutions.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://clinicaladvisorysolutions.com" # the base hostname & protocol for your site
twitter_username:
github_username:  quattromani

# Build settings
markdown: kramdown

exclude: ['node_modules', 'scss', 'DAM']

google_analytics: true
google_analytics_id: UA-50387096-8
jquery_version: 1.11.2

sitemap:
  file: "/sitemap.xml"
  exclude:
      - "/atom.xml"
      - "/feed.xml"
      - "/feed/index.xml"
  include_posts:
      - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priorit
