# Site settings
title: 'Clinical Advisory Solutions'
altTitle: 'CASLLC'
email: deborah.roy@clinicaladvisorysolutions.com
description: CAS delivers innovative solutions geared to maximize the quality of your support operations and strengthen your organization’s competitive position.
baseurl: ""
url: "http://clinicaladvisorysolutions.com"
phone: 910-200-4986
twitter_username:
github_username:  quattromani

# Build settings
markdown: kramdown

exclude: ['node_modules', 'scss', 'DAM']

google_analytics: true
google_analytics_id: UA-50387096-8
jquery_version: 1.11.2

sitemap:
  file: "/sitemap.xml"
  exclude:
      - "/atom.xml"
      - "/feed.xml"
      - "/feed/index.xml"
  include_posts:
      - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"
